<a href="https://colab.research.google.com/github/annnova2007/los-prediction-project/blob/main/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/ml project/dataset.csv')

/tmp/ipykernel_3193/2440508507.py:3: DtypeWarning: Columns (29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/drive/MyDrive/ml project/dataset.csv')

In [3]:
df.columns[29]

'Birth Weight'

In [4]:
df['Total Costs'] = (
    df['Total Costs']
    .astype(str)
    .str.replace(',', '', regex=True)
)

df['Total Costs'] = pd.to_numeric(df['Total Costs'], errors='coerce')

In [5]:
df['Total Costs'] = df['Total Costs'].fillna(df['Total Costs'].median())

In [6]:
df['Total Costs'] = df['Total Costs'].infer_objects(copy=False)

In [7]:
df['Total Costs'].dtype

dtype('float64')

In [8]:
df

,Health Service Area,Hospital County,Operating Certificate Number,Permanent Facility Id,Facility Name,Age Group,Zip Code,Gender,Race,Ethnicity,...,APR Severity of Illness Description,APR Risk of Mortality,APR Medical Surgical Description,Payment Typology 1,Payment Typology 2,Payment Typology 3,Birth Weight,Emergency Department Indicator,Total Charges,Total Costs
0,Hudson Valley,Westchester,5957001.0,1139.0,WESTCHESTER MEDICAL CENTER,0-17,OOS,F,White,Not Span/Hispanic,...,Moderate,Minor,Medical,Private Health Insurance,NaN,NaN,NaN,Y,46814.00,6772.07
1,New York City,Queens,7003001.0,1628.0,FLUSHING HOSPITAL MEDICAL CENTER,0-17,113,M,White,Spanish/Hispanic,...,Moderate,Moderate,Medical,Medicaid,NaN,NaN,NaN,Y,13490.00,15464.30
2,New York City,New York,7002054.0,1458.0,NEW YORK-PRESBYTERIAN HOSPITAL - NEW YORK WEIL...,70 or Older,100,M,White,Not Span/Hispanic,...,Moderate,Moderate,Medical,Medicare,Private Health Insurance,NaN,NaN,Y,49503.16,9324.77
3,New York City,New York,7002054.0,1464.0,NEW YORK-PRESBYTERIAN HOSPITAL - COLUMBIA PRES...,0-17,100,F,Other Race,Not Span/Hispanic,...,Minor,Minor,Medical,Private Health Insurance,NaN,NaN,2700,Y,27827.66,7304.27
4,New York City,New York,7002032.0,1466.0,MOUNT SINAI WEST,18-29,100,F,Other Race,Spanish/Hispanic,...,Moderate,Minor,Medical,Medicare,NaN,NaN,NaN,Y,32798.29,7948.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2196732,New York City,New York,7002024.0,1456.0,MOUNT SINAI HOSPITAL,70 or Older,111,F,Multi-racial,Not Span/Hispanic,...,Moderate,Moderate,Surgical,Medicare,Medicare,Medicaid,NaN,N,59727.81,17084.60
2196733,Central NY,Jefferson,2238700.0,379.0,CARTHAGE AREA HOSPITAL INC,18-29,136,F,White,Not Span/Hispanic,...,Minor,Minor,Surgical,Federal/State/Local/VA,NaN,NaN,NaN,N,25474.57,43365.68
2196734,New York City,Kings,7001016.0,1301.0,KINGS COUNTY HOSPITAL CENTER,30-49,112,F,Black/African American,Unknown,...,Moderate,Minor,Surgical,Medicaid,NaN,NaN,NaN,N,51617.21,28211.54
2196735,Long Island,Nassau,7002053.0,511.0,NYU LANGONE HOSPITAL-LONG ISLAND,30-49,117,F,White,Not Span/Hispanic,...,Major,Moderate,Medical,Blue Cross/Blue Shield,NaN,NaN,NaN,N,60404.55,19568.72
2196736,New York City,Kings,7001035.0,1318.0,WYCKOFF HEIGHTS MEDICAL CENTER,30-49,113,F,Other Race,Spanish/Hispanic,...,Minor,Minor,Medical,Private Health Insurance,NaN,NaN,NaN,Y,6179.07,2238.09

In [9]:
df.head()

,Health Service Area,Hospital County,Operating Certificate Number,Permanent Facility Id,Facility Name,Age Group,Zip Code,Gender,Race,Ethnicity,...,APR Severity of Illness Description,APR Risk of Mortality,APR Medical Surgical Description,Payment Typology 1,Payment Typology 2,Payment Typology 3,Birth Weight,Emergency Department Indicator,Total Charges,Total Costs
0,Hudson Valley,Westchester,5957001.0,1139.0,WESTCHESTER MEDICAL CENTER,0-17,OOS,F,White,Not Span/Hispanic,...,Moderate,Minor,Medical,Private Health Insurance,NaN,NaN,NaN,Y,46814.00,6772.07
1,New York City,Queens,7003001.0,1628.0,FLUSHING HOSPITAL MEDICAL CENTER,0-17,113,M,White,Spanish/Hispanic,...,Moderate,Moderate,Medical,Medicaid,NaN,NaN,NaN,Y,13490.00,15464.30
2,New York City,New York,7002054.0,1458.0,NEW YORK-PRESBYTERIAN HOSPITAL - NEW YORK WEIL...,70 or Older,100,M,White,Not Span/Hispanic,...,Moderate,Moderate,Medical,Medicare,Private Health Insurance,NaN,NaN,Y,49503.16,9324.77
3,New York City,New York,7002054.0,1464.0,NEW YORK-PRESBYTERIAN HOSPITAL - COLUMBIA PRES...,0-17,100,F,Other Race,Not Span/Hispanic,...,Minor,Minor,Medical,Private Health Insurance,NaN,NaN,2700,Y,27827.66,7304.27
4,New York City,New York,7002032.0,1466.0,MOUNT SINAI WEST,18-29,100,F,Other Race,Spanish/Hispanic,...,Moderate,Minor,Medical,Medicare,NaN,NaN,NaN,Y,32798.29,7948.10

DATA PREPROCESSING

In [10]:
df.shape

(2196737, 33)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2196737 entries, 0 to 2196736
Data columns (total 33 columns):
 #   Column                               Dtype
---  ------                               -----
 0   Health Service Area                  object
 1   Hospital County                      object
 2   Operating Certificate Number         float64
 3   Permanent Facility Id                float64
 4   Facility Name                        object
 5   Age Group                            object
 6   Zip Code                             object
 7   Gender                               object
 8   Race                                 object
 9   Ethnicity                            object
 10  Length of Stay                       object
 11  Type of Admission                    object
 12  Patient Disposition                  object
 13  Discharge Year                       int64
 14  CCSR Diagnosis Code                  object
 15  CCSR Diagnosis Description           object
 16  CCSR Procedure Code                  object
 17  CCSR Procedure Description           object
 18  APR DRG Code                         int64
 19  APR DRG Description                  object
 20  APR MDC Code                         int64
 21  APR MDC Description                  object
 22  APR Severity of Illness Code         int64
 23  APR Severity of Illness Description  object
 24  APR Risk of Mortality                object
 25  APR Medical Surgical Description     object
 26  Payment Typology 1                   object
 27  Payment Typology 2                   object
 28  Payment Typology 3                   object
 29  Birth Weight                         object
 30  Emergency Department Indicator       object
 31  Total Charges                        float64
 32  Total Costs                          float64
dtypes: float64(4), int64(4), object(25)
memory usage: 553.1+ MB

In [12]:
df.describe()

,Operating Certificate Number,Permanent Facility Id,Discharge Year,APR DRG Code,APR MDC Code,APR Severity of Illness Code,Total Charges,Total Costs
count,2.191442e+06,2.191442e+06,2196737.0,2.196737e+06,2.196737e+06,2.196737e+06,2.196737e+06,2.196737e+06
mean,5.087132e+06,1.279496e+03,2024.0,4.143324e+02,1.030294e+01,2.145497e+00,9.062543e+04,2.641658e+04
std,2.245914e+06,1.869344e+03,0.0,2.440963e+02,5.985493e+00,9.252315e-01,1.894022e+05,5.537229e+04
min,1.010000e+05,1.000000e+00,2024.0,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2.953000e+06,5.410000e+02,2024.0,1.940000e+02,5.000000e+00,1.000000e+00,2.357638e+04,7.415880e+03
50%,5.957001e+06,1.117000e+03,2024.0,3.830000e+02,9.000000e+00,2.000000e+00,4.724379e+04,1.411045e+04
75%,7.002032e+06,1.456000e+03,2024.0,6.400000e+02,1.500000e+01,3.000000e+00,9.451516e+04,2.778834e+04
max,7.004010e+06,1.562000e+04,2024.0,9.560000e+02,2.500000e+01,4.000000e+00,1.969486e+07,6.701232e+06

In [13]:
df.isnull().sum()

Health Service Area                       5295
Hospital County                           5295
Operating Certificate Number              5295
Permanent Facility Id                     5295
Facility Name                                0
Age Group                                    0
Zip Code                                 41972
Gender                                       0
Race                                         0
Ethnicity                                    0
Length of Stay                               0
Type of Admission                            0
Patient Disposition                          0
Discharge Year                               0
CCSR Diagnosis Code                          0
CCSR Diagnosis Description                   0
CCSR Procedure Code                     643764
CCSR Procedure Description              643764
APR DRG Code                                 0
APR DRG Description                          0
APR MDC Code                                 0
APR MDC Description                          0
APR Severity of Illness Code                 0
APR Severity of Illness Description          0
APR Risk of Mortality                        0
APR Medical Surgical Description             0
Payment Typology 1                         227
Payment Typology 2                     1204408
Payment Typology 3                     1956699
Birth Weight                           1988915
Emergency Department Indicator               0
Total Charges                                0
Total Costs                                  0
dtype: int64

In [14]:
# Drop columns with >50% missing values
threshold = len(df) * 0.5
df = df.dropna(thresh=threshold, axis=1)

In [15]:
# Fill categorical with "Unknown"
cat_cols = df.select_dtypes(include='object').columns
df.loc[:, cat_cols] = df.loc[:, cat_cols].fillna("Unknown")

In [16]:
# Numerical
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
exclude_cols = ['Operating Certificate Number', 'Permanent Facility Id']
num_cols = [col for col in num_cols if col not in exclude_cols]

medians = df[num_cols].median()
df.loc[:, num_cols] = df.loc[:, num_cols].fillna(medians)

In [17]:
#fixing datatypes
id_cols = [
    'Operating Certificate Number',
    'Permanent Facility Id'
]

df.loc[:, id_cols] = df.loc[:, id_cols].astype(str)

/tmp/ipykernel_3193/1824576298.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['5957001.0' '7003001.0' '7002054.0' ... '7001016.0' '7002053.0'
 '7001035.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, id_cols] = df.loc[:, id_cols].astype(str)
/tmp/ipykernel_3193/1824576298.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['1139.0' '1628.0' '1458.0' ... '1301.0' '511.0' '1318.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, id_cols] = df.loc[:, id_cols].astype(str)

In [18]:
df.dtypes

Health Service Area                     object
Hospital County                         object
Operating Certificate Number            object
Permanent Facility Id                   object
Facility Name                           object
Age Group                               object
Zip Code                                object
Gender                                  object
Race                                    object
Ethnicity                               object
Length of Stay                          object
Type of Admission                       object
Patient Disposition                     object
Discharge Year                           int64
CCSR Diagnosis Code                     object
CCSR Diagnosis Description              object
CCSR Procedure Code                     object
CCSR Procedure Description              object
APR DRG Code                             int64
APR DRG Description                     object
APR MDC Code                             int64
APR MDC Description                     object
APR Severity of Illness Code             int64
APR Severity of Illness Description     object
APR Risk of Mortality                   object
APR Medical Surgical Description        object
Payment Typology 1                      object
Emergency Department Indicator          object
Total Charges                          float64
Total Costs                            float64
dtype: object

In [19]:
# After filtering
df = df.copy()

# Then safe assignment
df.loc[:, 'Length of Stay'] = pd.to_numeric(df['Length of Stay'], errors='coerce')

In [20]:
df.loc[:, 'Emergency Department Indicator'] = df['Emergency Department Indicator'].map({
    'Y': 1,
    'N': 0
})

In [21]:
age_map = {
    '0-17': 0,
    '18-29': 1,
    '30-49': 2,
    '50-69': 3,
    '70 or Older': 4
}

df.loc[:, 'Age Group'] = df['Age Group'].map(age_map)

In [22]:
severity_map = {
    'Minor': 0,
    'Moderate': 1,
    'Major': 2,
    'Extreme': 3
}

df.loc[:, 'APR Severity of Illness Description'] = df['APR Severity of Illness Description'].map(severity_map)

In [23]:
mortality_map = {
    'Minor': 0,
    'Moderate': 1,
    'Major': 2,
    'Extreme': 3
}

df.loc[:, 'APR Risk of Mortality'] = df['APR Risk of Mortality'].map(mortality_map)

In [24]:
code_cols = [
    'APR DRG Code',
    'APR MDC Code',
    'APR Severity of Illness Code'
]

df.loc[:, code_cols] = df.loc[:, code_cols].astype('category')

In [25]:
cat_cols = [
    'Health Service Area',
    'Hospital County',
    'Facility Name',
    'Age Group',
    'Gender',
    'Race',
    'Ethnicity',
    'Type of Admission',
    'Patient Disposition',
    'CCSR Diagnosis Description',
    'CCSR Procedure Description',
    'APR DRG Description',
    'APR MDC Description',
    'APR Severity of Illness Description',
    'APR Risk of Mortality',
    'APR Medical Surgical Description',
    'Payment Typology 1'
]

df.loc[:, cat_cols] = df.loc[:, cat_cols].astype('category')

In [26]:
df['Zip Code'] = df['Zip Code'].astype(str)

In [27]:
df['CCSR Diagnosis Code'] = df['CCSR Diagnosis Code'].astype('category')
df['CCSR Procedure Code'] = df['CCSR Procedure Code'].astype('category')

In [28]:
# Final check
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2196737 entries, 0 to 2196736
Data columns (total 30 columns):
 #   Column                               Dtype
---  ------                               -----
 0   Health Service Area                  object
 1   Hospital County                      object
 2   Operating Certificate Number         object
 3   Permanent Facility Id                object
 4   Facility Name                        object
 5   Age Group                            object
 6   Zip Code                             object
 7   Gender                               object
 8   Race                                 object
 9   Ethnicity                            object
 10  Length of Stay                       object
 11  Type of Admission                    object
 12  Patient Disposition                  object
 13  Discharge Year                       int64
 14  CCSR Diagnosis Code                  category
 15  CCSR Diagnosis Description           object
 16  CCSR Procedure Code                  category
 17  CCSR Procedure Description           object
 18  APR DRG Code                         int64
 19  APR DRG Description                  object
 20  APR MDC Code                         int64
 21  APR MDC Description                  object
 22  APR Severity of Illness Code         int64
 23  APR Severity of Illness Description  object
 24  APR Risk of Mortality                object
 25  APR Medical Surgical Description     object
 26  Payment Typology 1                   object
 27  Emergency Department Indicator       object
 28  Total Charges                        float64
 29  Total Costs                          float64
dtypes: category(2), float64(2), int64(4), object(22)
memory usage: 477.7+ MB

In [29]:
df = df.copy()

df.loc[:, 'Length of Stay'] = pd.to_numeric(
    df['Length of Stay'], errors='coerce'
)

In [30]:
df['Length of Stay'].dtype

dtype('O')

In [31]:
df['Length of Stay'].unique()[:20]

array([1.0, 2.0, 3.0, 8.0, 9.0, 5.0, 4.0, 28.0, 6.0, 32.0, 48.0, 7.0,
       22.0, 18.0, 13.0, 39.0, 11.0, nan, 63.0, 114.0], dtype=object)

In [32]:
df['Length of Stay'] = df['Length of Stay'].astype(float)

In [33]:
df['Length of Stay'].dtype

dtype('float64')

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2196737 entries, 0 to 2196736
Data columns (total 30 columns):
 #   Column                               Dtype
---  ------                               -----
 0   Health Service Area                  object
 1   Hospital County                      object
 2   Operating Certificate Number         object
 3   Permanent Facility Id                object
 4   Facility Name                        object
 5   Age Group                            object
 6   Zip Code                             object
 7   Gender                               object
 8   Race                                 object
 9   Ethnicity                            object
 10  Length of Stay                       float64
 11  Type of Admission                    object
 12  Patient Disposition                  object
 13  Discharge Year                       int64
 14  CCSR Diagnosis Code                  category
 15  CCSR Diagnosis Description           object
 16  CCSR Procedure Code                  category
 17  CCSR Procedure Description           object
 18  APR DRG Code                         int64
 19  APR DRG Description                  object
 20  APR MDC Code                         int64
 21  APR MDC Description                  object
 22  APR Severity of Illness Code         int64
 23  APR Severity of Illness Description  object
 24  APR Risk of Mortality                object
 25  APR Medical Surgical Description     object
 26  Payment Typology 1                   object
 27  Emergency Department Indicator       object
 28  Total Charges                        float64
 29  Total Costs                          float64
dtypes: category(2), float64(3), int64(4), object(21)
memory usage: 477.7+ MB

In [35]:
df = df.copy()

# 1. Fix binary column
df.loc[:, 'Emergency Department Indicator'] = df[
    'Emergency Department Indicator'
].map({'Y': 1, 'N': 0})

# 2. Convert code columns to category
code_cols = [
    'APR DRG Code',
    'APR MDC Code',
    'APR Severity of Illness Code'
]
df.loc[:, code_cols] = df.loc[:, code_cols].astype('category')

# 3. Convert object columns to category
cat_cols = df.select_dtypes(include='object').columns
df.loc[:, cat_cols] = df.loc[:, cat_cols].astype('category')

# 4. Keep ID columns as string (VERY IMPORTANT)
id_cols = [
    'Operating Certificate Number',
    'Permanent Facility Id',
    'Zip Code'
]
df.loc[:, id_cols] = df.loc[:, id_cols].astype(str)

# Final check
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2196737 entries, 0 to 2196736
Data columns (total 30 columns):
 #   Column                               Dtype
---  ------                               -----
 0   Health Service Area                  object
 1   Hospital County                      object
 2   Operating Certificate Number         object
 3   Permanent Facility Id                object
 4   Facility Name                        object
 5   Age Group                            object
 6   Zip Code                             object
 7   Gender                               object
 8   Race                                 object
 9   Ethnicity                            object
 10  Length of Stay                       float64
 11  Type of Admission                    object
 12  Patient Disposition                  object
 13  Discharge Year                       int64
 14  CCSR Diagnosis Code                  category
 15  CCSR Diagnosis Description           object
 16  CCSR Procedure Code                  category
 17  CCSR Procedure Description           object
 18  APR DRG Code                         int64
 19  APR DRG Description                  object
 20  APR MDC Code                         int64
 21  APR MDC Description                  object
 22  APR Severity of Illness Code         int64
 23  APR Severity of Illness Description  object
 24  APR Risk of Mortality                object
 25  APR Medical Surgical Description     object
 26  Payment Typology 1                   object
 27  Emergency Department Indicator       object
 28  Total Charges                        float64
 29  Total Costs                          float64
dtypes: category(2), float64(3), int64(4), object(21)
memory usage: 477.7+ MB

In [36]:
print("Shape:", df.shape)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nUnique values:")
print(df.nunique().sort_values())

Shape: (2196737, 30)

Missing values:
Health Service Area                          0
Hospital County                              0
Operating Certificate Number                 0
Permanent Facility Id                        0
Facility Name                                0
Age Group                                    0
Zip Code                                     0
Gender                                       0
Race                                         0
Ethnicity                                    0
Length of Stay                            2404
Type of Admission                            0
Patient Disposition                          0
Discharge Year                               0
CCSR Diagnosis Code                          0
CCSR Diagnosis Description                   0
CCSR Procedure Code                          0
CCSR Procedure Description                   0
APR DRG Code                                 0
APR DRG Description                          0
APR MDC Code                                 0
APR MDC Description                          0
APR Severity of Illness Code                 0
APR Severity of Illness Description        456
APR Risk of Mortality                      456
APR Medical Surgical Description             0
Payment Typology 1                           0
Emergency Department Indicator         2196737
Total Charges                                0
Total Costs                                  0
dtype: int64

Duplicate rows:
16551

Unique values:
Emergency Department Indicator               0
Discharge Year                               1
APR Medical Surgical Description             3
Gender                                       3
APR Risk of Mortality                        4
APR Severity of Illness Description          4
Race                                         4
Ethnicity                                    4
Age Group                                    5
APR Severity of Illness Code                 5
Type of Admission                            6
Health Service Area                          9
Payment Typology 1                          10
Patient Disposition                         19
APR MDC Description                         26
APR MDC Code                                26
Zip Code                                    51
Hospital County                             58
Length of Stay                             119
Operating Certificate Number               159
Facility Name                              203
Permanent Facility Id                      206
CCSR Procedure Code                        321
CCSR Procedure Description                 321
APR DRG Code                               336
APR DRG Description                        336
CCSR Diagnosis Description                 478
CCSR Diagnosis Code                        478
Total Costs                            1677228
Total Charges                          1926585
dtype: int64

In [37]:
# ============================================
# STEP: Fix Datatypes (corrected)
# ============================================

df = df.copy()

# --- Identifier columns → string ---
id_cols = ['Operating Certificate Number', 'Permanent Facility Id', 'Zip Code']
for col in id_cols:
    df[col] = df[col].astype(str)

# --- Numeric columns ---
df['Length of Stay'] = pd.to_numeric(df['Length of Stay'], errors='coerce')
df['Discharge Year'] = pd.to_numeric(df['Discharge Year'], errors='coerce').astype('int64')
df['Total Charges'] = pd.to_numeric(df['Total Charges'], errors='coerce')
df['Total Costs'] = pd.to_numeric(df['Total Costs'], errors='coerce')

# --- Binary indicator ---
df['Emergency Department Indicator'] = df['Emergency Department Indicator'].map({'Y': 1, 'N': 0}).astype('Int64')

# --- Code columns → category ---
code_cols = ['APR DRG Code', 'APR MDC Code', 'APR Severity of Illness Code']
for col in code_cols:
    df[col] = df[col].astype('category')

# --- Remaining categorical/text columns → category ---
cat_cols = [
    'Health Service Area', 'Hospital County', 'Facility Name', 'Age Group',
    'Gender', 'Race', 'Ethnicity', 'Type of Admission', 'Patient Disposition',
    'CCSR Diagnosis Code', 'CCSR Diagnosis Description',
    'CCSR Procedure Code', 'CCSR Procedure Description',
    'APR DRG Description', 'APR MDC Description',
    'APR Severity of Illness Description', 'APR Risk of Mortality',
    'APR Medical Surgical Description', 'Payment Typology 1'
]
cat_cols = [c for c in cat_cols if c in df.columns]
for col in cat_cols:
    df[col] = df[col].astype('category')

# --- Verify ---
print(df.dtypes)

Health Service Area                    category
Hospital County                        category
Operating Certificate Number             object
Permanent Facility Id                    object
Facility Name                          category
Age Group                              category
Zip Code                                 object
Gender                                 category
Race                                   category
Ethnicity                              category
Length of Stay                          float64
Type of Admission                      category
Patient Disposition                    category
Discharge Year                            int64
CCSR Diagnosis Code                    category
CCSR Diagnosis Description             category
CCSR Procedure Code                    category
CCSR Procedure Description             category
APR DRG Code                           category
APR DRG Description                    category
APR MDC Code                           category
APR MDC Description                    category
APR Severity of Illness Code           category
APR Severity of Illness Description    category
APR Risk of Mortality                  category
APR Medical Surgical Description       category
Payment Typology 1                     category
Emergency Department Indicator            Int64
Total Charges                           float64
Total Costs                             float64
dtype: object

In [38]:
print("Rows before dedup:", len(df))

# Check how many exact duplicate rows exist
dup_count = df.duplicated().sum()
print("Exact duplicate rows found:", dup_count)

# Drop exact duplicates
df = df.drop_duplicates()

print("Rows after dedup:", len(df))

Rows before dedup: 2196737
Exact duplicate rows found: 16551
Rows after dedup: 2180186

In [39]:
# ============================================
# STEP: Encode Categorical Variables (Option A)
# ============================================

# --- Ordinal mappings (apply to both versions, since these are genuinely ordinal) ---
age_map = {
    '0-17': 0,
    '18-29': 1,
    '30-49': 2,
    '50-69': 3,
    '70 or Older': 4
}

severity_map = {
    'Minor': 0,
    'Moderate': 1,
    'Major': 2,
    'Extreme': 3
}

df['Age Group'] = df['Age Group'].map(age_map)
df['APR Severity of Illness Description'] = df['APR Severity of Illness Description'].map(severity_map)
df['APR Risk of Mortality'] = df['APR Risk of Mortality'].map(severity_map)

# ============================================
# BRANCH 1: df_encoded  →  Linear Regression, Random Forest, XGBoost
# ============================================

df_encoded = df.copy()

# Low-cardinality nominal → one-hot
low_card_cols = [
    'Gender', 'Race', 'Ethnicity', 'Type of Admission',
    'Patient Disposition', 'APR Medical Surgical Description',
    'Payment Typology 1'
]
low_card_cols = [c for c in low_card_cols if c in df_encoded.columns]
df_encoded = pd.get_dummies(df_encoded, columns=low_card_cols, drop_first=True)

# High-cardinality nominal → frequency encoding
high_card_cols = [
    'Health Service Area', 'Hospital County', 'Facility Name',
    'CCSR Diagnosis Code', 'CCSR Diagnosis Description',
    'CCSR Procedure Code', 'CCSR Procedure Description',
    'APR DRG Description', 'APR MDC Description',
    'Zip Code'
]
high_card_cols = [c for c in high_card_cols if c in df_encoded.columns]

for col in high_card_cols:
    freq = df_encoded[col].value_counts(normalize=True)
    df_encoded[col + '_freq'] = df_encoded[col].map(freq)

df_encoded = df_encoded.drop(columns=high_card_cols)

# APR code columns → keep as category, but Linear Reg/RF/XGB(sklearn) need numeric
# so cast to int for these three models
code_cols = ['APR DRG Code', 'APR MDC Code', 'APR Severity of Illness Code']
for col in code_cols:
    df_encoded[col] = df_encoded[col].astype(int)

print("df_encoded shape:", df_encoded.shape)
print(df_encoded.dtypes)

# ============================================
# BRANCH 2: df_catboost  →  CatBoost (native categorical handling)
# ============================================

df_catboost = df.copy()

# CatBoost needs categorical columns as string or category dtype (not float/object mix)
cat_features = [
    'Health Service Area', 'Hospital County', 'Facility Name',
    'Gender', 'Race', 'Ethnicity', 'Type of Admission', 'Patient Disposition',
    'CCSR Diagnosis Code', 'CCSR Diagnosis Description',
    'CCSR Procedure Code', 'CCSR Procedure Description',
    'APR DRG Description', 'APR MDC Description',
    'APR Medical Surgical Description', 'Payment Typology 1',
    'Zip Code', 'APR DRG Code', 'APR MDC Code', 'APR Severity of Illness Code'
]
cat_features = [c for c in cat_features if c in df_catboost.columns]

for col in cat_features:
    df_catboost[col] = df_catboost[col].astype(str)  # CatBoost wants string, not pandas category

print("df_catboost shape:", df_catboost.shape)
print("Categorical features for CatBoost:", cat_features)

df_encoded shape: (2180186, 65)
Operating Certificate Number         object
Permanent Facility Id                object
Age Group                           float64
Length of Stay                      float64
Discharge Year                        int64
                                     ...
CCSR Procedure Code_freq            float64
CCSR Procedure Description_freq     float64
APR DRG Description_freq            float64
APR MDC Description_freq           category
Zip Code_freq                       float64
Length: 65, dtype: object
df_catboost shape: (2180186, 30)
Categorical features for CatBoost: ['Health Service Area', 'Hospital County', 'Facility Name', 'Gender', 'Race', 'Ethnicity', 'Type of Admission', 'Patient Disposition', 'CCSR Diagnosis Code', 'CCSR Diagnosis Description', 'CCSR Procedure Code', 'CCSR Procedure Description', 'APR DRG Description', 'APR MDC Description', 'APR Medical Surgical Description', 'Payment Typology 1', 'Zip Code', 'APR DRG Code', 'APR MDC Code', 'APR Severity of Illness Code']

In [40]:
print(len(df_encoded), len(df_catboost))

2180186 2180186

In [41]:
# ============================================
# STEP: Redo — Drop leakage columns, then handle LOS outliers properly
# ============================================

# --- 1. Drop leakage columns (known only after/during stay) ---
leak_cols = ['Total Charges', 'Total Costs']
df_encoded = df_encoded.drop(columns=[c for c in leak_cols if c in df_encoded.columns])
df_catboost = df_catboost.drop(columns=[c for c in leak_cols if c in df_catboost.columns])

# --- 2. Cap (winsorize) Length of Stay at 1st/99th percentile instead of dropping rows ---
lower_cap = df_encoded['Length of Stay'].quantile(0.01)
upper_cap = df_encoded['Length of Stay'].quantile(0.99)
print(f"Length of Stay caps: lower={lower_cap}, upper={upper_cap}")

df_encoded['Length of Stay'] = df_encoded['Length of Stay'].clip(lower_cap, upper_cap)
df_catboost['Length of Stay'] = df_catboost['Length of Stay'].clip(lower_cap, upper_cap)

print("Rows retained:", len(df_encoded), len(df_catboost))
print(df_encoded['Length of Stay'].describe())

Length of Stay caps: lower=1.0, upper=40.0
Rows retained: 2180186 2180186
count    2.177785e+06
mean     5.515765e+00
std      6.555853e+00
min      1.000000e+00
25%      2.000000e+00
50%      3.000000e+00
75%      6.000000e+00
max      4.000000e+01
Name: Length of Stay, dtype: float64

In [42]:
# Drop rows where target is missing
df_encoded = df_encoded.dropna(subset=['Length of Stay']).reset_index(drop=True)
df_catboost = df_catboost.dropna(subset=['Length of Stay']).reset_index(drop=True)

print(len(df_encoded), len(df_catboost))

2177785 2177785

In [43]:
# Save both versions so teammates don't need to rerun preprocessing
df_encoded.to_pickle('/content/drive/MyDrive/ml project/df_encoded.pkl')
df_catboost.to_pickle('/content/drive/MyDrive/ml project/df_catboost.pkl')

print("Saved successfully")

Saved successfully